[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[start]
cmd = "python3 bot.py"
